package postadmin::Model::Postfix;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'postadmin::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:postfix',
        user => 'root',
        password => '',
    }
);

=head1 NAME

postadmin::Model::Postfix - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<postadmin>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<postadmin::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.29

=head1 AUTHOR

Diego Kuperman

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
